# Generated by Django 3.2.9 on 2021-12-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Manage', '0002_auto_20211211_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
