# Generated by Django 3.2.9 on 2021-12-13 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User_Manage', '0003_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')])),
                ('phone', models.CharField(max_length=20, verbose_name='电话号码')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ManyToManyField(to='User_Manage.Department_staff')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User_Manage.school')),
            ],
        ),
    ]
